---
- name: Restart Nagios
  ansible.builtin.service:
    name: nagios4
    enabled: true
    state: restarted

- name: Restart Apache
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: restarted

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    enabled: true
    state: restarted
